#!/bin/bash

time=$(($2 * 60))
dtime=`date +"%m-%d-%Y %H:%M:%S"`
logstr=$dtime" Zone "$1" for "$2" min"
echo $logstr

onstr=`Rain8Net -v -d "/dev/ttyUSB0" -c on -u 1 -z $1`
if [[ $onstr != *SUCCESS* ]]; then
    echo $dtime" ON FAIL: "$onstr
    exit 1
fi

sleep $time

offstr=`Rain8Net -v -d "/dev/ttyUSB0" -c off -u 1 -z $1`
while [[ $offstr != *SUCCESS* ]]; do
    echo $dtime" OFF FAIL: "$offstr
    offstr=`Rain8Net -v -d "/dev/ttyUSB0" -c off -u 1 -z $1`
    sleep 5
done

echo "OK"
exit 0

