#!/bin/bash

# Command for running zone directly for n minutes.
#
#  e.g. zone_run /dev/ttyUSB0 0 10
#
# Rain8net is flaky! Sometimes error code is returned 
# when command succeeded.

time=$(($3 * 60))
dtime=`date +"%m-%d-%Y %H:%M:%S"`
logstr=$dtime" Zone "$2" for "$3" min"
echo $logstr

for i in `seq 1 5`; do
  if ./zone_on ${1} ${2}; then
    break
  fi
  sleep 1
done

sleep $time

while [ 1 ]; do
  if ./zone_off ${1} ${2}; then
    break
  fi  
  sleep 1
done

echo "OK - Run"
exit 0

